// Auto-generated by page-object-generate — 2026-05-19
// Edit locators in: e2e/page-objects/AdoptPage.ts

import { test, expect } from '@playwright/test';
import { AdoptPage } from '../page-objects';

// ── Mock data ───────────────────────────────────────────────────────────────
const CAT_ID = 'test-cat-001';
const MOCK_CAT = {
  id: CAT_ID,
  url: 'https://cataas.com/cat/test-cat-001',
  tags: ['cute', 'fluffy'],
};

// Intercept the external cataas API so tests run offline & deterministically
async function mockCatApi(page: ReturnType<typeof test.info>['project'] extends infer P ? never : import('@playwright/test').Page) {
  await page.route(
    `**/cat/${CAT_ID}/says/**`,
    (route) => route.fulfill({ status: 200, json: MOCK_CAT })
  );
}

// ── Tests ────────────────────────────────────────────────────────────────────
test.describe('Adopt page — Auto Generated', () => {
  let adopt: AdoptPage;

  test.beforeEach(async ({ page }) => {
    adopt = new AdoptPage(page);
    await mockCatApi(page);
  });

  // ── Load ──────────────────────────────────────────────────────────────────
  test('should load the adoption wizard', async ({ page }) => {
    await test.step('Navigate to adopt page', async () => {
      await adopt.navigate(CAT_ID);
    });
    await test.step('Verify wizard loaded', async () => {
      await adopt.waitForLoad();
      await expect(adopt.steps).toBeVisible();
      await expect(adopt.nextButton).toBeVisible();
    });
  });

  // ── Step 0 controls visible ───────────────────────────────────────────────
  test('should display Step 0 applicant controls', async ({ page }) => {
    await test.step('Navigate', async () => {
      await adopt.navigate(CAT_ID);
    });
    await test.step('Verify Step 0 controls are visible', async () => {
      await expect(adopt.fullNameInput).toBeVisible();
      await expect(adopt.ageInput).toBeVisible();
      await expect(adopt.phoneInput).toBeVisible();
      await expect(adopt.lineIdInput).toBeVisible();
    });
  });

  // ── Step 0 → Step 1 navigation ────────────────────────────────────────────
  test('should advance from Step 0 to Step 1 with valid data', async ({ page }) => {
    await test.step('Navigate', async () => {
      await adopt.navigate(CAT_ID);
    });
    await test.step('Fill Step 0', async () => {
      await adopt.fillStep0({ fullName: 'Jane Doe', age: 25, phone: '0812345678' });
    });
    await test.step('Click Next', async () => {
      await adopt.goToNextStep();
    });
    await test.step('Verify Step 1 controls are visible', async () => {
      await expect(adopt.homeTypeHouseButton).toBeVisible();
      await expect(adopt.homeTypeCondoButton).toBeVisible();
      await expect(adopt.homeTypeOtherButton).toBeVisible();
      await expect(adopt.hasPetsSelect).toBeVisible();
    });
  });

  // ── Step 0 validation ─────────────────────────────────────────────────────
  test('should block Step 0 → Step 1 when required fields are empty', async ({ page }) => {
    await test.step('Navigate', async () => {
      await adopt.navigate(CAT_ID);
    });
    await test.step('Click Next without filling anything', async () => {
      await adopt.goToNextStep();
    });
    await test.step('Verify we are still on Step 0', async () => {
      await expect(adopt.fullNameInput).toBeVisible();
    });
  });

  // ── Step 1 — home type selection ──────────────────────────────────────────
  test('should select home type on Step 1', async ({ page }) => {
    await test.step('Navigate and complete Step 0', async () => {
      await adopt.navigate(CAT_ID);
      await adopt.fillStep0({ fullName: 'Jane Doe', age: 25, phone: '0812345678' });
      await adopt.goToNextStep();
    });
    await test.step('Select home type "House"', async () => {
      await adopt.selectHomeType('house');
      await expect(adopt.homeTypeHouseButton).toHaveClass(/ant-radio-button-wrapper-checked/);
    });
  });

  // ── Step 1 — petDetails shown when hasPets = Yes ──────────────────────────
  test('should show pet details textarea when hasPets = Yes', async ({ page }) => {
    await test.step('Navigate and complete Step 0', async () => {
      await adopt.navigate(CAT_ID);
      await adopt.fillStep0({ fullName: 'Jane Doe', age: 25, phone: '0812345678' });
      await adopt.goToNextStep();
    });
    await test.step('Select "Yes" for has pets', async () => {
      await adopt.selectHomeType('house');
      await adopt.selectHasPets('Yes');
    });
    await test.step('Verify Pet Details textarea appears', async () => {
      await expect(adopt.petDetailsTextArea).toBeVisible();
    });
  });

  // ── Step 1 — petDetails hidden when hasPets = No ──────────────────────────
  test('should hide pet details textarea when hasPets = No', async ({ page }) => {
    await test.step('Navigate and complete Step 0', async () => {
      await adopt.navigate(CAT_ID);
      await adopt.fillStep0({ fullName: 'Jane Doe', age: 25, phone: '0812345678' });
      await adopt.goToNextStep();
    });
    await test.step('Select "No" for has pets', async () => {
      await adopt.selectHomeType('condo');
      await adopt.selectHasPets('No');
    });
    await test.step('Verify Pet Details textarea is hidden', async () => {
      await expect(adopt.petDetailsTextArea).not.toBeVisible();
    });
  });

  // ── Step 2 — agreement visible ────────────────────────────────────────────
  test('should show agreement checkbox on Step 2', async ({ page }) => {
    await test.step('Navigate and complete Steps 0–1', async () => {
      await adopt.navigate(CAT_ID);
      await adopt.fillStep0({ fullName: 'Jane Doe', age: 25, phone: '0812345678' });
      await adopt.goToNextStep();
      await adopt.fillStep1({ homeType: 'house', hasPets: 'No' });
      await adopt.goToNextStep();
    });
    await test.step('Verify agreement checkbox is visible', async () => {
      await expect(adopt.agreeCheckbox).toBeVisible();
      await expect(adopt.submitButton).toBeVisible();
    });
  });

  // ── Previous button navigation ────────────────────────────────────────────
  test('should navigate back to Step 0 via Previous button', async ({ page }) => {
    await test.step('Navigate to Step 1', async () => {
      await adopt.navigate(CAT_ID);
      await adopt.fillStep0({ fullName: 'Jane Doe', age: 25, phone: '0812345678' });
      await adopt.goToNextStep();
    });
    await test.step('Click Previous', async () => {
      await adopt.goToPreviousStep();
    });
    await test.step('Verify back on Step 0', async () => {
      await expect(adopt.fullNameInput).toBeVisible();
    });
  });

  // ── Happy path full submit ─────────────────────────────────────────────────
  test('should submit application and show success result', async ({ page }) => {
    await test.step('Navigate', async () => {
      await adopt.navigate(CAT_ID);
    });
    await test.step('Complete Step 0', async () => {
      await adopt.fillStep0({ fullName: 'Jane Doe', age: 25, phone: '0812345678' });
      await adopt.goToNextStep();
    });
    await test.step('Complete Step 1', async () => {
      await adopt.fillStep1({ homeType: 'house', hasPets: 'No' });
      await adopt.goToNextStep();
    });
    await test.step('Agree and submit', async () => {
      await adopt.checkAgree();
      await adopt.submitApplication();
    });
    await test.step('Verify success result', async () => {
      await expect(adopt.successResult).toBeVisible();
      await expect(adopt.backToHomeLink).toBeVisible();
    });
  });
});
